name: Deploy

# Run deployment to Github packages on commits to the `master` branch
on:
  push:
    branches:
      - master
      - v2

jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: Set up Java for publishing to GitHub Packages
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Publish to GitHub Packages
        run: mvn clean deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

