name: Deploy

# Run deployment to OSSRH
on:
  push:
    branches:
      - main

jobs:
  deploy-ossrh:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Java for publishing
        uses: actions/setup-java@v1
        with:
          java-version: 11
          server-id: ossrh
          server-username: MAVEN_USERNAME
          server-password: MAVEN_PASSWORD
      - name: Publish package
        run: mvn clean --batch-mode deploy
        env:
          MAVEN_USERNAME: ${{ secrets.OSSRH_USER}}
          MAVEN_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}

  deploy-docker:
    name: Publish - Docker Hub
    runs-on: ubuntu-18.04
    env:
      REPO: dxworks/githubminer
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v1
      - name: Set up Java for publishing to Docker Hub
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Build target
        run: mvn clean package
      - name: Login to Docker Hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }}
          -p ${{ secrets.DOCKER_PASSWORD }}
      - name: Build Docker image
        run: docker build -t $REPO:latest -t $REPO:${GITHUB_SHA::8} .
      - name: Publish Docker image
        run: docker push $REPO
